spring:
  application:
    name: @artifactId@
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    schema: classpath:db/h2/schema.sql
    data: classpath:db/h2/data.sql
server:
  port: 80
liquibase:
  enabled: false
meicloud:
  security:
    browser:
      login-page: /login